### ISSUE TITLE
Small Display Issue

### ISSUE THREAD

**Issue by Cubiccl** [Darkxell/EDMHouse#1]
In the Title - Artist - Title - Artist moving text, the - between Title and Artist disappears when it reaches the left side

**Comment by Darkxell** [comment]
Indeed. Working on it.

**Comment by Darkxell** [comment]
Issue fixed.
Turned out to be a skin problem, so comunity skins that uses old layout.edm values might suffer from that problem in the future. Unlikely tho...
Thanks for feedback.
